// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "search-country-system/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ICountryService is an autogenerated mock type for the ICountryService type
type ICountryService struct {
	mock.Mock
}

// GetCountryData provides a mock function with given fields: ctx, name
func (_m *ICountryService) GetCountryData(ctx context.Context, name string) (dto.Country, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCountryData")
	}

	var r0 dto.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.Country, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.Country); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(dto.Country)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICountryService creates a new instance of ICountryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICountryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICountryService {
	mock := &ICountryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
